using System.Reflection.Metadata;
using System.Xml.Linq;
using Tyuiu.SushchikIA.Sprint1.Task1.V8.Lib;

DataService ds = new DataService();
Console.Title = "Спринт #1 | Выполнил: Сущик И.А. | ПИНб-25-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #1                                                               *");
Console.WriteLine("* Тема: Базовые навыки работы в C#                                        *");
Console.WriteLine("* Задание #0                                                              *");
Console.WriteLine("* Вариант #14                                                             *");
Console.WriteLine("* Выполнил: Сущик Игорь Александрович | ПИНб-25-1                         *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                *");
Console.WriteLine("* Написать программу, которая вычисляет выражение 2 * 3 * 3 + 7           *");
Console.WriteLine("* И печатает результат на экране                                          *");
Console.WriteLine("*                                                                         *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                        *");
Console.WriteLine("* 2 * 3 * 3 + 7                                                           *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("*                                                                         *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                              *");
Console.WriteLine("***************************************************************************");
string xStr = Console.ReadLine();
string aStr = Console.ReadLine();
double x = Convert.ToDouble(xStr);
double a = Convert.ToDouble(aStr);
Console.WriteLine(ds.Calculate(a, x));
Console.ReadLine();