using Tyuiu.SushchikIA.Sprint1.Task7.V1.Lib;
DataService ds = new DataService();
Console.Title = "Спринт #1 | Выполнил: Сущик И.А. | ПИНб-25-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #1                                                               *");
Console.WriteLine("* Тема: Базовые навыки работы в C#                                        *");
Console.WriteLine("* Задание #7                                                              *");
Console.WriteLine("* Вариант #1                                                             *");
Console.WriteLine("* Выполнил: Сущик Игорь Александрович | ПИНб-25-1                         *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                *");
Console.WriteLine("* Написать программу, которая вычисляет выражение                         *");
Console.WriteLine("* И печатает результат на экране                                          *");
Console.WriteLine("*                                                                         *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                        *");
string a = Console.ReadLine();
string b = Console.ReadLine();
string c = Console.ReadLine();
double aDouble = Convert.ToDouble(a);
double bDouble = Convert.ToDouble(b);
double cDouble = Convert.ToDouble(c);
Console.WriteLine("***************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                              *");
Console.WriteLine("***************************************************************************");
Console.WriteLine(ds.Calculate(aDouble, bDouble, cDouble));
Console.ReadLine();